### ISSUE TITLE
Error while running the code

### ISSUE THREAD

**Issue by rishijagdev1** [wengong-jin/chemprop#21]
Hi, sorry if the question is a little noobish, but I get the following error while running the code : 

```
(chemprop) C:\Users\1901566.admin\Downloads\chemprop-master>python web/run.py
Traceback (most recent call last):
  File "web/run.py", line 10, in <module>
    from app import app, db
  File "C:\Users\1901566.admin\Downloads\chemprop-master\web\app\__init__.py", line 6, in <module>
    app.config.from_object('config')
  File "C:\Users\1901566.admin\.conda\envs\chemprop\lib\site-packages\flask\config.py", line 174, in from_object
    obj = import_string(obj)
  File "C:\Users\1901566.admin\.conda\envs\chemprop\lib\site-packages\werkzeug\utils.py", line 568, in import_string
    __import__(import_name)
  File "C:\Users\1901566.admin\Downloads\chemprop-master\web\config.py", line 9, in <module>
    import torch
  File "C:\Users\1901566.admin\.conda\envs\chemprop\lib\site-packages\torch\__init__.py", line 81, in <module>
    ctypes.CDLL(dll)
  File "C:\Users\1901566.admin\.conda\envs\chemprop\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

Could anyone  please please help me solve this? I don't know the reason of this error.

**Comment by wengong-jin** [comment]
Hi,

This repo is outdated. Please check the most recent version: https://github.com/chemprop/chemprop
