### ISSUE TITLE
predict.py AssertionError

### ISSUE THREAD

**Issue by chupvl** [wengong-jin/chemprop#6]
python predict.py --test_path data/tox21.csv --checkpoint_dir tox21_checkpoints --preds_path tox21_preds.csv

Traceback (most recent call last):
  File "predict.py", line 6, in <module>
    make_predictions(args)
  File "/home/chupvl/git/chemprop/chemprop/train/make_predictions.py", line 30, in make_predictions
    assert smiles is not None  # Note: Currently only works with smiles provided, not with data file.
AssertionError

**Comment by swansonk14** [comment]
Fixed in [this commit](https://github.com/wengong-jin/chemprop/commit/81cc176dd76b79f353cf9bf402477b7513c844bf)
